"""
Regenerate sim.mjs from index.html.

The physics core is NOT duplicated by hand — it is sliced straight out of
index.html by section marker, so the headless sim can never drift from the game.
Re-run this after every edit to index.html.
"""
import re, sys

src = open('index.html', encoding='utf-8').read().splitlines()


def find_section(n):
    """Return the 0-based line index of the content just after section header n."""
    pat = re.compile(r'^\s+' + re.escape(n) + r'\.\s')
    for i, ln in enumerate(src):
        if pat.match(ln):
            return i + 2          # skip the closing ═══ line
    raise SystemExit(f'section {n} not found')


core = src[find_section('1'):find_section('4') - 3]      # 1, 2, 2b, 3
reset = src[find_section('7'):find_section('8') - 3]     # resetCast

body = '\n'.join(core) + '\n\n' + '\n'.join(reset)

# The Trout class lives in section 5, which we drop. physics() only ever reaches
# it through `hooked`, which stays null in the headless harness.
body = body.replace("let hooked=null;", "let hooked=null;\nconst fishes=[];")
# resetCast() calls handTargets() from section 6; setHand() does that job here
body = body.replace("  handTargets();_p0.copy(_k0);", "  _p0.copy(_k0);")
# let the harness pin ITER so the adaptive rule can be A/B'd against a fixed count
body = body.replace("    ITER=iterFor(nAct);", "    ITER=ITER_PIN||iterFor(nAct);")
body = body.replace("let ITER=6;", "let ITER=6; let ITER_PIN=0;")
# expose solver iteration counts so the harness can sweep them

header = """/* AUTO-GENERATED by build-sim.py from index.html — do not edit by hand.
   Physics core only: settings, state, grid, solver, resetCast.
   Scene, trout meshes, panels, controllers and the render loop are excluded. */
import * as THREE from './three-stub.mjs';
"""

footer = """

/* ── headless driver surface ───────────────────────────────────────────────
   The game drives the rod from a tracked controller. Everything downstream of
   the two driven butt nodes is identical, so a scripted caster only has to
   supply a hand pose. This mirrors handTargets() from section 6. */
const BUTT_Z=0.175, NEXT_Z=BUTT_Z-ROD_SEG;
const _o=new THREE.Vector3();
const HAND_Q=new THREE.Quaternion();

let prevHandActive=0;
export function setHand(px,py,pz,q){
  HAND_Q.copy(q);
  _k0.set(px,py,pz);
  gdown.set(0,-1,0).applyQuaternion(q);
  _k1.copy(_k0).add(_o.set(0,0,NEXT_Z).applyQuaternion(q));
  _k0.add(_o.set(0,0,BUTT_Z).applyQuaternion(q));
  _reelW.copy(_k0).sub(_o.set(0,0,BUTT_Z).applyQuaternion(q))
        .add(_o.set(0,-0.076,0.20).applyQuaternion(q));
  _corkW.copy(_k0).sub(_o.set(0,0,BUTT_Z).applyQuaternion(q))
        .add(_o.set(0,-0.016,-0.045).applyQuaternion(q));
}

export function setLineHand(px,py,pz,mode){
  _handW.set(px,py,pz); _lhX=px; _lhY=py; _lhZ=pz;
  handMode=mode;
}
let _lhX=0,_lhY=0,_lhZ=0;

/* the parts of the main loop that touch line state, without any rendering */
export function stepInputs(dt){
  const handActive=handMode>0;
  if(handActive&&handMode===1){
    const Dg=Math.hypot(_lhX-guidePos[0],_lhY-guidePos[1],_lhZ-guidePos[2]);
    handArc=Math.min(offSpool-0.15,(lineOut+rodArc)+Dg+0.14);
    handIdx=Math.max(1,Math.round(idxAt(handArc)));
    if(Dg>1.2) handIdx=-1;
  } else if(handActive&&prevHandActive!==2&&handMode===2){
    const n=nearestLineNode(_lhX,_lhY,_lhZ);
    if(n.i>0&&n.d<0.22){
      handArc=sArc(n.i)+(sArc(n.i+1)-sArc(n.i))*n.t;
      grabArc=handArc;
      handIdx=Math.max(1,Math.round(idxAt(handArc)));
      const a=n.i*3,b=a+3;
      _grabFrom.set(pos[a]+(pos[b]-pos[a])*n.t,
                    pos[a+1]+(pos[b+1]-pos[a+1])*n.t,
                    pos[a+2]+(pos[b+2]-pos[a+2])*n.t);
      grabEase=0;
    } else handIdx=-1;
  }
  if(!handActive) handIdx=-1;
  prevHandActive=handActive?handMode:0;
  handHeld=handActive&&handIdx>0;
  handPinched=handMode===2&&handIdx>0;
  grabEase=handPinched?Math.min(1,grabEase+dt*4):1;
  {const e=grabEase*grabEase*(3-2*grabEase);
   _grabW.lerpVectors(_grabFrom,_handW,e);}
}

export function setSolver(sub,iter){ ITER_PIN=iter||0; }   /* 0 = use the adaptive rule */
export function getSolver(){ return {SUB,ITER}; }
export function setFlag(k,v){
  if(k==='rodPinch') rodPinch=v;
  else if(k==='reeling') reeling=v;
}

export function nearestLineNodeExport(x,y,z){ return nearestLineNode(x,y,z); }

/* nearestLineNode lives in section 6, so it is restated here verbatim */
function nearestLineNode(x,y,z){
  let best=-1,bd=1e9,bt=0;
  const from=Math.max(1,Math.floor(idxAt(lineOut+rodArc))+1);
  const to=Math.min(nAct-3,Math.floor(idxAt(offSpool))-2);
  for(let i=from;i<=to;i++){
    const a=i*3,b=a+3;
    const ex=pos[b]-pos[a],ey=pos[b+1]-pos[a+1],ez=pos[b+2]-pos[a+2];
    const ll=ex*ex+ey*ey+ez*ez;
    let t=ll>1e-9?((x-pos[a])*ex+(y-pos[a+1])*ey+(z-pos[a+2])*ez)/ll:0;
    t=Math.max(0,Math.min(1,t));
    const px=pos[a]+ex*t-x, py=pos[a+1]+ey*t-y, pz=pos[a+2]+ez*t-z;
    const d=px*px+py*py+pz*pz;
    if(d<bd){bd=d;best=i;bt=t;}
  }
  return {i:best,d:Math.sqrt(bd),t:bt};
}

export function state(){
  return {lineOut, offSpool, nAct, rodArc, wrapTotal,
          probeOut, probeIn, probeThr, blewUp, handIdx, handMode,
          slipOut, spoolOut, grabEase};
}
export function clearBlewUp(){ blewUp=false; }
export function applyPreset_(o){ for(const k in o) if(k in P) P[k]=o[k]; }

export {
  P, PHYSICAL, CLASSIC, physics, resetCast, rebuildRod, rebuildMasses,
  rebuildSpacing, redistribute, sArc, idxAt, restOf, nodeSpan, lineProfile,
  pos, vel, rpos, rvel, invM, dragK, guidePos, updateGuidePositions,
  RN, ROD_SEG, ROD_LEN, NG, MAXNODE, TOTAL_LINE, FLYLINE_LEN,
  surfY, bedY, bedDepth, filmY, OBST, CZ, HALFW,
  _k0, _k1, _p0, _p1, _reelW, _corkW, _handW, gdown,
};
"""

out = header + '\n' + body + footer
open('sim.mjs', 'w', encoding='utf-8').write(out)
print(f'sim.mjs written — {len(out.splitlines())} lines '
      f'({len(core)} core + {len(reset)} reset)')
